apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - infrastructure/postgresql
  - infrastructure/redis
  - infrastructure/kafka
  - auth-service
  - backend
  - frontend
  - ingress.yaml
