apiVersion: v1
kind: Service
metadata:
  name: portfolio-dashboard
  namespace: portfolio
  labels:
    app: portfolio-dashboard
spec:
  type: ClusterIP
  selector:
    app: portfolio-dashboard
  ports:
    - name: http
      port: 80
      targetPort: 80


